---
# vars file for postgres

    pg_repo_key: "https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-12"
    pg_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    pg_version: "postgresql12-server"
    pg_init: "postgresql-12-setup initdb postgresql-12 --encoding=UTF8"
    pg_start_command: "name={{ item }} state=started enabled=yes"
    pg_data: "/var/lib/pgsql/12/data"
    pg_service: "postgresql-12"
    pg_bin: /usr/pgsql-12/bin/

    db_user: test
    db_password: test
    user_ip: 10.10.10.111

    db_name: postgres
    backup_dir: /opt/backups
